eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://${EUREKA_HOST_NAME:3.235.144.86}:8761/eureka/

  instance:
    hostname: ${EUREKA_HOST_NAME:3.235.144.86}
